default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
        exclude: ^(\.vscode|\.devcontainer)/
      - id: check-added-large-files
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: "isort ./backend"
        language: "python"
  - repo: https://github.com/google/yapf
    rev: v0.33.0
    hooks:
      - id: yapf
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-c", "backend/pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ["--rcfile=backend/pyproject.toml"]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        stages: [commit]
        types: [python]
        entry: mypy
        language: system
        args:
          [
            "--follow-imports=silent",
            "--ignore-missing-imports",
            "--show-column-numbers",
            "--no-pretty",
            "--config-file=./backend/pyproject.toml",
          ]
