default_language_version:
    python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: isort # custom isort hook because of python3.10 compatibility problems
        name: isort
        entry: "isort ./backend"
        language: "python"
  - repo: https://github.com/google/yapf
    rev: v0.33.0
    hooks:
      - id: yapf

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    - id: bandit
      args: ["-c", "backend/pyproject.toml"]
      additional_dependencies: ["bandit[toml]"]
