version: '3.9'

services:

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: >-
      ash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
      - 5678:5678
    depends_on:
      - postgres
    env_file:
      - .env
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./.pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  redis-commander:
    container_name: redis-commander
    image: ghcr.io/joeferner/redis-commander
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      - redis
    volumes:
      - ./redis-commander-local.json:/redis-commander/config/local.json

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    ports:
      - "15672:15672" # management
      - "5672:5672" # communication
    restart: unless-stopped

  celery-worker:
    container_name: celery-worker
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: celery -A backend worker -l info
    volumes:
      - ./backend:/app
    depends_on:
      - rabbitmq
    env_file:
      - .env
    restart: unless-stopped

  celery-beat:
    container_name: celery-beat
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: celery -A backend beat -l info
    volumes:
      - ./backend:/app
    depends_on:
      - rabbitmq
    env_file:
      - .env
    restart: unless-stopped

  flower:
    container_name: flower
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: celery -A backend flower
    ports:
      - "5555:5555"
    volumes:
      - ./backend:/app
    depends_on:
      - rabbitmq
    env_file:
      - .env
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    depends_on:
      - postgres
    ports:
      - "5050:80"
    restart: unless-stopped
    volumes:
      - ./pgadmin-servers.json:/pgadmin4/servers.json

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    restart: unless-stopped

  mkdocs:
    container_name: mkdocs
    image: squidfunk/mkdocs-material
    volumes:
      - ./docs:/docs/
    ports:
      - "7000:8000"
    restart: unless-stopped

  coverage:
    container_name: coverage
    image: halverneus/static-file-server
    volumes:
      - ./backend/htmlcov:/web
    ports:
      - "8888:8080"
    restart: unless-stopped
