version: '3.9'
# overrides backend service, run with: `docker compose -f docker-compose.yml -f docker-compose.debug.yml up`

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: >-
      ash -c "python manage.py migrate && python -m debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading --noreload"
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
      - 5678:5678
      - 5679:5679 # run shell debugger here
    depends_on:
      - postgres
    env_file:
      - .env
    restart: unless-stopped
