version: '3.9'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: >-
      ash -c " python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./.pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    depends_on:
      - postgres
    ports:
      - "5050:80"
    restart: unless-stopped
    volumes:
      - ./pgadmin-servers.json:/pgadmin4/servers.json

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    restart: unless-stopped

  mkdocs:
    image: squidfunk/mkdocs-material
    volumes:
      - ./docs:/docs/
    ports:
      - "8001:8000"
