FROM python:3.10-bullseye

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN mkdir /app
WORKDIR /app

RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
	gcc \
	musl-dev \
	libpq-dev \
	libffi-dev

RUN wget -O - https://install.python-poetry.org | python3 -
ENV PATH="/root/.local/bin:${PATH}"

COPY pyproject.toml poetry.lock /app/

RUN poetry config virtualenvs.create false \
	&& poetry install --no-interaction --no-ansi
