FROM python:3.10-alpine

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN mkdir /app
WORKDIR /app

RUN apk update \
	&& apk add --no-cache \
	gcc \
	musl-dev \
	postgresql-dev \
	libffi-dev

RUN wget -O - https://install.python-poetry.org | python3 -
ENV PATH="/root/.local/bin:${PATH}"

COPY pyproject.toml poetry.lock /app/

RUN poetry config virtualenvs.create false \
	&& poetry install --no-interaction --no-ansi
