FROM mcr.microsoft.com/devcontainers/python:3.10
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
	&& apt-get -y install git


RUN	/usr/local/bin/python3.10 -m pip install -U poetry bandit pylama flake8 isort pre-commit
