site_name: Todo API docs
site_url: http://127.0.0.1:8000
theme:
  name: material
  palette:
    primary: "blue"
nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Usage: getting-started/usage.md
