name: test backend
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          set -x
          docker version
          cp dev/.env .env
          docker compose up -d backend postgres
          ./run-cmd.sh pytest --cov-report term
