name: test backend
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: abatilo/actions-poetry@v2
      - run: |
          set -x
          cd backend
          cp env/dev.env .env
          docker compose up -d postgres
          poetry install
          poetry shell
          pytest --cov-report term
